#!/bin/bash
pyfile=$PYFILE
output_file="${pyfile}c"

python3 - << END
import py_compile

try:
    py_compile.compile("$pyfile", cfile="$output_file")
    print("Compiling $pyfile ...")
    exit(0)
except Exception as e:
    print(f"Compilation failed: {e}")
    exit(1)
END
